import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.css';
import {DemoNavigation} from '@/components/demo-navigation';
import Image from 'next/image';
import shad from './shad.jpeg';
import {ThemeProvider} from '@/components/theme-provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <div className="grid min-h-screen gap-16 font-[family-name:var(--font-geist-sans)]">
        <div className="flex items-center justify-center  w-full gap-16">
          <h1 className="text-3xl font-bold">shadcn/ui demo</h1>
          <Image src={shad} alt="shadcn" width={100} height={100} />
          <DemoNavigation />
        </div>

        <main className="grid justify-items-center items-center gap-8 row-start-2 w-full h-full">
          {children}
        </main>
      </div>
    </ThemeProvider>
    </body>
    </html>
  );
}
